### ISSUE TITLE
Tests fail on i686

### ISSUE THREAD

**Issue by QuLogic** [HenrikBengtsson/R.devices#33]
Every once in a while, [automated test rebuilds](https://koschei.fedoraproject.org/package/R-R.devices?collection=f32) will run on 32-bit system, and fail:
```
  +   } ## if (arch$endian == .Platform$endian)
  + } ## for (kk ...)
  - File #1 ('/builddir/build/BUILD/R.devices/R.devices.Rcheck/R.devices/exdata/capturePlot,engine=11,ostype=unix,arch=i686,ptrsize=4,endian=little.rds') ...
  List of 4
   $ ostype : chr "unix"
   $ arch   : chr "i686"
   $ ptrsize: int 4
   $ endian : chr "little"
  List of 4
   $ ostype : chr "unix"
   $ arch   : chr NA
   $ ptrsize: int 4
   $ endian : chr "little"
  Error: identical(g8_1b, g8_1) is not TRUE
  Execution halted
```
I _think_ this may be because there's a [special case](https://github.com/HenrikBengtsson/R.devices/blob/develop/R/recordedplot-methods.R#L109-L114) for i386 and x86_64, but not i686 (or i486 or i586)?

**Comment by HenrikBengtsson** [comment]
Thanks. I'll look into this.

Just for my clarification on where "once in a while" in

> Every once in a while, automated test rebuilds will run on 32-bit system, and fail

belong. Are you saying this happens every time it runs on that 32-bit platform, correct?  And it's only once in a while tests are run on that platform. In other words, is this 100% reproducible on that machine?

**Comment by QuLogic** [comment]
Yes, since R.devices doesn't have any compiled code and thus isn't arch-specific, the rebuilds happen on random builders. Unfortunately, the last build to happen on x86(_64) happened some time ago so there's no log to say whether it was 64-bit or 32-bit. In that time, it's possible that some other update may be a confounding factor (e.g., R 3.5.3-> 3.6.0 or 3.6.1).

However, locally I can run in a 32-bit mock chroot and get the error, so it is definitely 100% reproducible with current packages.

**Comment by HenrikBengtsson** [comment]
UPDATE:
I can reproduce this on my old 32-bit Ubuntu 16.04 (arch=i686) with R 3.6.1.  I've actually tested on this machine for almost all new releases of R.devices, but I've done so using R 3.4.3 - the latest version that came with Ubuntu 16.04 - and that never failed.  The test i686 file was actually created on that machine.

So, now, I've built R 3.6.1 from source allowing me to reproduce the error. This will help me to make the tests agile to "unknown" architectures.  Right now, I suspect there might have been changes to the internal data structures of recorded plots.

I'll see what I can do and when, but I'll make sure to fix this before the next release.

**Comment by HenrikBengtsson** [comment]
Hi, finally, 13 months later I revived my old Thinkpad X60 with 32-bit Ubuntu 16.04 (arch=i686) and managed to reproduce this error and then also fix it for my case without turning to special cases, cf. commit c245132.  

@QuLogic, I don't know if this will help in your case but I hope so.  I have a hard CRAN deadline for Jan 21 (Issue #35), which I mean I plan to submit early Jan 19. If you have a chance to try this out before then, that would be awesome.  If not, I can do another submission quite quickly thereafter.

To test locally:

```r
git clone git@github.com:HenrikBengtsson/R.devices.git
git checkout develop ## should be the default
R CMD build R.devices
R CMD check R.devices_2.16.1-9000.tar.gz
```

Thank you

**Comment by QuLogic** [comment]
I ran `develop` on an i686 mock build, and it passed all the tests successfully.

**Comment by HenrikBengtsson** [comment]
Brilliant. I appreciate it.

**Comment by HenrikBengtsson** [comment]
R.devices 2.17.0 rolls out on CRAN right now.  Hopefully, you'll see zero issues from this package on the Fedora build/test system.
